# Generated by Django 5.1.6 on 2025-02-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_instance_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='instance_id',
            field=models.IntegerField(null=True),
        ),
    ]
