# Generated by Django 5.1.4 on 2025-01-03 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('cidr', models.CharField(max_length=50, null=True)),
                ('driver', models.CharField(choices=[('bridge', 'Bridge'), ('overlay', 'Overlay'), ('host', 'Host'), ('macvlan', 'MacVLAN'), ('none', 'None')], default='bridge', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('directory', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('paused', 'Paused'), ('created', 'Created')], max_length=50)),
                ('image_name', models.CharField(default='hello-world', max_length=100)),
                ('http_host_port', models.IntegerField()),
                ('https_host_port', models.IntegerField()),
                ('ssh_host_port', models.IntegerField()),
                ('detach', models.BooleanField(default=True)),
                ('ssh_access', models.BooleanField(default=False)),
                ('https_access', models.BooleanField(default=True)),
                ('directory', models.CharField(max_length=255)),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='dha.network')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='dha.user')),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mount_point', models.CharField(max_length=255, null=True)),
                ('mount_type', models.CharField(choices=[('ro', 'Read-Only'), ('rw', 'Read-Write')], default='rw', max_length=2)),
                ('attached_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volumes', to='dha.instance')),
            ],
        ),
    ]
