# Generated by Django 5.1.4 on 2025-01-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='https_host_port',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='ssh_host_port',
            field=models.IntegerField(null=True),
        ),
    ]
