# Generated by Django 5.1.6 on 2025-02-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dha', '0002_alter_instance_https_host_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='image_name',
            field=models.CharField(default='gitlab/gitlab-ce:latest', max_length=100),
        ),
        migrations.AlterField(
            model_name='instance',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
